services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always

winpty docker run -it -e POSTGRES_USER="root" -e POSTGRES_PASSWORD="root" -e POSTGRES_DB="ny_taxi" -v c:/Users/VINICIUS/Desktop/programs/"Friendly tutorials"/"Data Engineering"/"DE Zoomcamp"/data-engineering-zoomcamp/01-docker-terraform/2_docker_sql/ny_taxi_postgres_data:/var/lib/postgresql/data -p 5432:5432 postgres:13


winpty docker run -it -e PGADMIN_DEFAULT_EMAIL="admin@admin.com" -e PGADMIN_DEFAULT_PASSWORD="root" -p 8080:80 --network=pg-network --name pgadmin-2 dpage/pgadmin4

COPY taxi_zone_lookup(LocationID, Borough, Zone, service_zone)
FROM '/c/Users/VINICIUS/Desktop/programs/Friendly tutorials/Data Engineering/DE Zoomcamp/data-engineering-zoomcamp/01-docker-terraform/2_docker_sql
/taxi_zone_lookup.csv'
DELIMITER ','
CSV HEADER;


\COPY taxi_zone_lookup(LocationID, Borough, Zone, service_zone) FROM 'c:/Users/VINICIUS/Desktop/programs/Friendly tutorials/Data Engineering/DE Zoomcamp/data-engineering-zoomcamp/01-docker-terraform/2_docker_sql/taxi_zone_lookup.csv' WITH (FORMAT csv, HEADER true)